name: GÜNCELE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Her saat başı (eğer biri durursa diğeri başlasın diye güvenlik önlemi)

jobs:
  non-stop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Dependencies
        run: pip install requests
      - name: Run 2026 Bot
        # DİKKAT: -u parametresi GitHub'ın kodun çalıştığını anlamasını sağlar!
        run: python -u hepsi.py 
